# Default
root:
    pattern:  /
    defaults: { _controller: DahlbergPodrBundle:Default:index }

dashboard:
    pattern:  /dashboard
    defaults: { _controller: DahlbergPodrBundle:Default:dashboard }

# Account
account_create:
    path:     /account/create
    defaults: { _controller: DahlbergPodrBundle:Account:create }

account_index:
    path:     /account
    defaults:  { _controller: DahlbergPodrBundle:Account:index }

account_login:
    path:     /login
    defaults:  { _controller: DahlbergPodrBundle:Account:login }

account_login_check:
    path:     /login_check

account_logout:
    path:     /logout

account_register:
    path:     /account/register
    defaults: { _controller: DahlbergPodrBundle:Account:register }

# Episode
episode_archive:
    path:     /episode/{id}/archive
    defaults: { _controller: DahlbergPodrBundle:Episode:archive }

episode_details:
    path:     /episode/{id}
    defaults: { _controller: DahlbergPodrBundle:Episode:details }

episode_dislike:
    path:     /episode/{id}/dislike
    defaults: { _controller: DahlbergPodrBundle:Episode:dislike }

episode_index:
    path:     /episode
    defaults: { _controller: DahlbergPodrBundle:Episode:index }

episode_like:
    path:     /episode/{id}/like
    defaults: { _controller: DahlbergPodrBundle:Episode:like }

episode_restore:
    path:     /episode/{id}/restore
    defaults: { _controller: DahlbergPodrBundle:Episode:restore }

episode_stash:
    path:     /episode/{id}/stash
    defaults: { _controller: DahlbergPodrBundle:Episode:stash }

episode_unstash:
    path:     /episode/{id}/unstash
    defaults: { _controller: DahlbergPodrBundle:Episode:unstash }

episode_updatetime:
    path:     /episode/{id}/updatetime/{time}
    defaults: { _controller: DahlbergPodrBundle:Episode:updateTime, time: -1 }

# Playlist
playlist_index:
    path:     /playlist
    defaults: { _controller: DahlbergPodrBundle:Playlist:index }

# Podcast
podcast_index:
    path:     /podcast
    defaults: { _controller: DahlbergPodrBundle:Podcast:index }

podcast_import:
    path:     /podcast/import
    defaults: { _controller: DahlbergPodrBundle:Podcast:import }

podcast_details:
    path:     /podcast/{id}
    defaults: { _controller: DahlbergPodrBundle:Podcast:details }

podcast_dislike:
    path:      /podcast/{id}/dislike
    defaults:  { _controller: DahlbergPodrBundle:Podcast:dislike }

podcast_follow:
    path:      /podcast/{id}/follow
    defaults:  { _controller: DahlbergPodrBundle:Podcast:follow }

podcast_like:
    path:      /podcast/{id}/like
    defaults:  { _controller: DahlbergPodrBundle:Podcast:like }

podcast_star:
    path:      /podcast/{id}/star
    defaults:  { _controller: DahlbergPodrBundle:Podcast:star }

podcast_unfollow:
    path:      /podcast/{id}/unfollow
    defaults:  { _controller: DahlbergPodrBundle:Podcast:unfollow }

podcast_unstar:
    path:      /podcast/{id}/unstar
    defaults:  { _controller: DahlbergPodrBundle:Podcast:unstar }

podcast_update:
    path:      /podcast/{id}/update
    defaults:  { _controller: DahlbergPodrBundle:Podcast:update }

# Search
search_index:
    path:      /search
    defaults:  { _controller: DahlbergPodrBundle:Search:index }

# API V1
api_v1_get_episode:
    path:     /api/v1/episode/{id}
    defaults: { _controller: DahlbergPodrBundle:Episode:getEpisode }
api_v1_patch_userepisode:
    path:     /api/v1/userepisode/patch/{id}
    defaults: { _controller: DahlbergPodrBundle:Episode:patchUserEpisode }