root:
    pattern:  /
    defaults: { _controller: DahlbergPodrBundle:Default:index }

account_create:
    path:     /account/create
    defaults: { _controller: DahlbergPodrBundle:Account:create }

account_index:
    path:     /account
    defaults:  { _controller: DahlbergPodrBundle:Account:index }

account_login:
    path:     /login
    defaults:  { _controller: DahlbergPodrBundle:Account:login }

account_login_check:
    path:     /login_check

account_logout:
    path:     /logout

account_register:
    path:     /account/register
    defaults: { _controller: DahlbergPodrBundle:Account:register }

podcast_index:
    path:     /podcast
    defaults: { _controller: DahlbergPodrBundle:Podcast:index }