root:
    pattern:  /
    defaults: { _controller: DahlbergPodrBundle:Default:index }

# Account
account_create:
    path:     /account/create
    defaults: { _controller: DahlbergPodrBundle:Account:create }

account_index:
    path:     /account
    defaults:  { _controller: DahlbergPodrBundle:Account:index }

account_login:
    path:     /login
    defaults:  { _controller: DahlbergPodrBundle:Account:login }

account_login_check:
    path:     /login_check

account_logout:
    path:     /logout

account_register:
    path:     /account/register
    defaults: { _controller: DahlbergPodrBundle:Account:register }

# Episode
episode_details:
    path:     /episode/{id}
    defaults: { _controller: DahlbergPodrBundle:Episode:details }

# Podcast
podcast_details:
    path:     /podcast/{id}
    defaults: { _controller: DahlbergPodrBundle:Podcast:details }

podcast_dislike:
    path:      /podcast/{id}/dislike
    defaults:  { _controller: DahlbergPodrBundle:Podcast:dislike }

podcast_follow:
    path:      /podcast/{id}/follow
    defaults:  { _controller: DahlbergPodrBundle:Podcast:follow }

podcast_index:
    path:     /podcast
    defaults: { _controller: DahlbergPodrBundle:Podcast:index }

podcast_like:
    path:      /podcast/{id}/like
    defaults:  { _controller: DahlbergPodrBundle:Podcast:like }

podcast_star:
    path:      /podcast/{id}/star
    defaults:  { _controller: DahlbergPodrBundle:Podcast:star }

podcast_unfollow:
    path:      /podcast/{id}/unfollow
    defaults:  { _controller: DahlbergPodrBundle:Podcast:unfollow }

podcast_unstar:
    path:      /podcast/{id}/unstar
    defaults:  { _controller: DahlbergPodrBundle:Podcast:unstar }

podcast_update:
    path:      /podcast/{id}/update
    defaults:  { _controller: DahlbergPodrBundle:Podcast:update }