root:
    pattern:  /
    defaults: { _controller: DahlbergPodrBundle:Default:index }

# Account
account_create:
    path:     /account/create
    defaults: { _controller: DahlbergPodrBundle:Account:create }

account_index:
    path:     /account
    defaults:  { _controller: DahlbergPodrBundle:Account:index }

account_login:
    path:     /login
    defaults:  { _controller: DahlbergPodrBundle:Account:login }

account_login_check:
    path:     /login_check

account_logout:
    path:     /logout

account_register:
    path:     /account/register
    defaults: { _controller: DahlbergPodrBundle:Account:register }

# Episode
episode_details:
    path:     /episode/{id}
    defaults: { _controller: DahlbergPodrBundle:Episode:details }

# Podcast
podcast_details:
    path:     /podcast/{id}
    defaults: { _controller: DahlbergPodrBundle:Podcast:details }

podcast_index:
    path:     /podcast
    defaults: { _controller: DahlbergPodrBundle:Podcast:index }

podcast_update:
    path:      /podcast/{id}/update
    defaults:  { _controller: DahlbergPodrBundle:Podcast:update }